apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: golang-exam
  name: golang-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-exam
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: golang-exam
    spec:
      containers:
      - image: jamshid01994/golangapp:v4
        name: golangapp
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: info
              key: env
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: info
              key: log_leveI
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: db-sec
              key: DB_URI
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: info
              key: grpc_port
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources: {}
status: {}
